base_url = "https://tontinton.com"

title = "tontinton"

compile_sass = true
build_search_index = false
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
toc = false
use_cdn = false

theme = "toggle" # light, dark, auto, toggle

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/tontinton/", icon = "github" },
    { name = "email", url = "mailto:tony.solomonik@gmail.com", icon = "email" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
]

custom_css = []
