// Short links: every piece in static/voxel/pieces.json with a `short` name is also served at /v/<short>/
// (e.g. tontinton.com/v/cot → the cottage). The short page is a copy of the piece's index.html with
// <base href="/voxel/<slug>/">, so the URL stays short and every relative path still resolves; it carries
// a canonical link to the real page. Works on any static host (no redirects/rewrites needed).
//
//   node links.mjs            regenerate static/v/ from pieces.json (new.mjs runs this for you)
//   node links.mjs --check    exit 1 if static/v/ is stale (test.mjs runs this check too)
//
// After editing a piece's index.html, title or short name: rerun `node links.mjs`.
//
// Cache busting: it also stamps every piece's index.html with an import map that gives each module
// (the piece's own .js files and everything in static/voxel/lib/) a content-hash query (`./people.js` →
// `./people.js?v=3f2a…`), and loads `./scene.js?v=…`. A changed file gets a new URL, so no browser or CDN
// edge cache can serve a stale module after a deploy; unchanged files keep their URL and stay cached.
// So: after editing ANY .js of a piece or the lib, rerun `node links.mjs` (test.mjs fails when stale).
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const STATIC = resolve(here, '../../static');
const MARK = '<!-- generated by voxel/tools/links.mjs from /voxel/';
export const SHORT_RE = /^[a-z0-9][a-z0-9-]{0,15}$/;

export function readPieces() {
  return JSON.parse(readFileSync(resolve(STATIC, 'voxel/pieces.json'), 'utf8'));
}

/** Problems with the manifest's short names (missing pieces, bad names, duplicates). */
export function validate(pieces) {
  const errs = [], seen = new Map();
  for (const p of pieces) {
    if (!p.short) continue;
    if (!SHORT_RE.test(p.short)) errs.push(`${p.slug}: short "${p.short}" must match ${SHORT_RE}`);
    if (seen.has(p.short)) errs.push(`${p.slug}: short "${p.short}" is already used by ${seen.get(p.short)}`);
    seen.set(p.short, p.slug);
    if (!existsSync(resolve(STATIC, 'voxel', p.slug, 'index.html'))) errs.push(`${p.slug}: static/voxel/${p.slug}/index.html not found`);
  }
  return errs;
}

const MAP_BEGIN = '<!-- modules: generated by voxel/tools/links.mjs (content hashes, cache busting) -->';
const MAP_END = '<!-- /modules -->';
const SCRIPT_RE = /<script type="module" src="\.\/scene\.js(\?v=[0-9a-f]+)?"><\/script>/;
const hash = (f) => createHash('sha1').update(readFileSync(f)).digest('hex').slice(0, 10);
function jsFiles(dir) {
  const out = [];
  for (const n of readdirSync(dir)) {
    const f = resolve(dir, n);
    if (statSync(f).isDirectory()) out.push(...jsFiles(f));
    else if (n.endsWith('.js')) out.push(f);
  }
  return out.sort();
}

/** A piece's index.html with the import map + versioned entry script (unchanged if it has no ./scene.js entry). */
export function stamped(slug, html) {
  if (!SCRIPT_RE.test(html)) return html;
  const dir = resolve(STATIC, 'voxel', slug), imports = {};
  for (const f of [...jsFiles(dir), ...jsFiles(resolve(STATIC, 'voxel/lib'))]) {
    let rel = relative(dir, f).split(sep).join('/');
    if (!rel.startsWith('.')) rel = './' + rel;
    imports[rel] = `${rel}?v=${hash(f)}`;
  }
  const block = `${MAP_BEGIN}\n<script type="importmap">\n${JSON.stringify({ imports }, null, 1)}\n</script>\n${MAP_END}\n`;
  const entry = `<script type="module" src="${imports['./scene.js'] ?? './scene.js'}"></script>`;
  const i = html.indexOf(MAP_BEGIN), j = html.indexOf(MAP_END);
  const bare = i >= 0 && j > i ? html.slice(0, i) + html.slice(j + MAP_END.length + 1) : html;
  return bare.replace(SCRIPT_RE, block + entry);
}

/** The /v/<short>/ page for a piece, from its index.html. */
export function shortPage(piece, html) {
  const base = `/voxel/${piece.slug}/`;
  const head = `\n${MARK}${piece.slug}/ — edit that page and rerun node links.mjs -->\n<base href="${base}">\n<link rel="canonical" href="https://tontinton.com${base}">`;
  // right after <meta charset> (or <head>): before anything with a relative URL
  const at = /<meta charset[^>]*>/i.test(html) ? /<meta charset[^>]*>/i : /<head>/i;
  if (!at.test(html)) throw new Error(`static/voxel/${piece.slug}/index.html has no <head>`);
  return html.replace(at, (m) => m + head);
}

/** { path: content } of every short page that should exist. */
export function expected(pieces = readPieces()) {
  const out = {};
  for (const p of pieces) if (p.short) out[`v/${p.short}/index.html`] = shortPage(p, readFileSync(resolve(STATIC, 'voxel', p.slug, 'index.html'), 'utf8'));
  return out;
}

/** Generated short pages that are stale, missing, or no longer in the manifest (+ pieces with stale module hashes). */
export function stale(pieces = readPieces()) {
  const want = expected(pieces), bad = [];
  for (const p of pieces) {
    const f = resolve(STATIC, 'voxel', p.slug, 'index.html');
    if (existsSync(f)) { const h = readFileSync(f, 'utf8'); if (stamped(p.slug, h) !== h) bad.push(`voxel/${p.slug}/index.html (module hashes)`); }
  }
  for (const [path, html] of Object.entries(want)) {
    const f = resolve(STATIC, path);
    if (!existsSync(f) || readFileSync(f, 'utf8') !== html) bad.push(path);
  }
  for (const d of existsSync(resolve(STATIC, 'v')) ? readdirSync(resolve(STATIC, 'v')) : []) {
    const f = resolve(STATIC, 'v', d, 'index.html');
    if (!want[`v/${d}/index.html`] && existsSync(f) && readFileSync(f, 'utf8').includes(MARK)) bad.push(`v/${d}/index.html (orphan)`);
  }
  return bad;
}

export function write(pieces = readPieces()) {
  for (const p of pieces) {
    const f = resolve(STATIC, 'voxel', p.slug, 'index.html');
    if (existsSync(f)) { const h = readFileSync(f, 'utf8'), n = stamped(p.slug, h); if (n !== h) writeFileSync(f, n); }
  }
  const want = expected(pieces);
  for (const [path, html] of Object.entries(want)) {
    mkdirSync(dirname(resolve(STATIC, path)), { recursive: true });
    writeFileSync(resolve(STATIC, path), html);
  }
  // remove pages generated for shorts that were renamed or deleted (never touches hand-made files)
  for (const d of existsSync(resolve(STATIC, 'v')) ? readdirSync(resolve(STATIC, 'v')) : []) {
    const f = resolve(STATIC, 'v', d, 'index.html');
    if (!want[`v/${d}/index.html`] && existsSync(f) && readFileSync(f, 'utf8').includes(MARK)) rmSync(resolve(STATIC, 'v', d), { recursive: true });
  }
  return Object.keys(want);
}

/** A free short name for a slug: its first 3 letters, then longer prefixes, then a number. */
export function suggest(slug, pieces = readPieces()) {
  const used = new Set(pieces.map((p) => p.short).filter(Boolean));
  const s = slug.replace(/[^a-z0-9]/g, '');
  for (let n = 3; n <= Math.min(s.length, 8); n++) if (!used.has(s.slice(0, n))) return s.slice(0, n);
  for (let i = 2; ; i++) if (!used.has(`${s.slice(0, 3)}${i}`)) return `${s.slice(0, 3)}${i}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const pieces = readPieces();
  const errs = validate(pieces);
  if (errs.length) { console.error(errs.join('\n')); process.exit(1); }
  if (process.argv.includes('--check')) {
    const bad = stale(pieces);
    if (bad.length) { console.error(`stale short links / module hashes (run node links.mjs):\n  ${bad.join('\n  ')}`); process.exit(1); }
    console.log('short links up to date');
  } else {
    for (const p of write(pieces)) console.log(`static/${p}  →  https://tontinton.com/${p.replace(/index\.html$/, '')}`);
    const missing = pieces.filter((p) => !p.short).map((p) => p.slug);
    if (missing.length) console.log(`no short name (add "short" in pieces.json): ${missing.join(', ')}`);
  }
}
